server:
  port: 3000
  base-url: /inventario
db:
  description: base de prueba
  host: localhost
  port: 5433
  database: inventario_db
  schema: inventario
  user: inventario_admin
  password: cambiar_esta_clave
install:
  dump:
    drop-his: false
    db:
      owner: inventario_owner
client-setup: 
  lang: es
devel:
  delay: 0
log:
  db:
    on-demand: true